/**
 * Tests for lib/clone-and-config.ts — handleUrlStart decision tree:
 *   1. gh auth → gh repo clone → git ssh → git https fallbacks
 *   2. existing clone reuse
 *   3. existing YAML reuse vs auto-generate
 */

import { describe, it, expect, vi, beforeEach, afterEach } from "vitest";
import { mkdtempSync, rmSync, writeFileSync, mkdirSync } from "node:fs";
import { join } from "node:path";
import { tmpdir } from "node:os";

const { mockExec, mockExecSilent, mockEnsureGit, mockFindFreePort } = vi.hoisted(() => ({
  mockExec: vi.fn(),
  mockExecSilent: vi.fn(),
  mockEnsureGit: vi.fn(),
  mockFindFreePort: vi.fn(),
}));

vi.mock("../../src/lib/shell.js", () => ({
  exec: mockExec,
  execSilent: mockExecSilent,
}));

vi.mock("../../src/lib/installer.js", () => ({
  ensureGit: mockEnsureGit,
}));

vi.mock("../../src/lib/web-dir.js", () => ({
  findFreePort: mockFindFreePort,
}));

vi.mock("ora", () => ({
  default: () => ({
    start: vi.fn().mockReturnThis(),
    succeed: vi.fn().mockReturnThis(),
    fail: vi.fn().mockReturnThis(),
    stop: vi.fn().mockReturnThis(),
    text: "",
  }),
}));

import { handleUrlStart } from "../../src/lib/clone-and-config.js";

let workDir: string;

beforeEach(() => {
  mockExec.mockReset();
  mockExecSilent.mockReset();
  mockEnsureGit.mockReset().mockResolvedValue(undefined);
  mockFindFreePort.mockReset().mockResolvedValue(3000);
  vi.spyOn(console, "log").mockImplementation(() => {});

  workDir = mkdtempSync(join(tmpdir(), "ao-clone-test-"));
  vi.spyOn(process, "cwd").mockReturnValue(workDir);
});

afterEach(() => {
  vi.restoreAllMocks();
  rmSync(workDir, { recursive: true, force: true });
});

describe("handleUrlStart", () => {
  it("reuses an existing YAML config when present in the clone target", async () => {
    const targetDir = join(workDir, "bar");
    const gitDir = join(targetDir, ".git");
    mkdirSync(gitDir, { recursive: true });
    writeFileSync(
      join(gitDir, "config"),
      `[remote "origin"]\n\turl = https://github.com/foo/bar.git\n`,
    );

    writeFileSync(
      join(targetDir, "agent-orchestrator.yaml"),
      `port: 3000\nprojects:\n  bar:\n    name: bar\n    path: ${targetDir}\n    defaultBranch: main\n`,
    );

    const result = await handleUrlStart("https://github.com/foo/bar");

    expect(result.autoGenerated).toBe(false);
    expect(result.parsed.ownerRepo).toBe("foo/bar");
    // No clone should have been attempted — directory already had a matching remote
    expect(mockExec).not.toHaveBeenCalled();
  });

  it("auto-generates YAML when the clone target has no config", async () => {
    const targetDir = join(workDir, "new-repo");

    mockExecSilent.mockResolvedValue(null);
    let gitCloneCalls = 0;
    mockExec.mockImplementation(async (cmd: string, args: string[]) => {
      if (cmd === "git" && args[0] === "clone") {
        gitCloneCalls++;
        if (gitCloneCalls === 1) {
          throw new Error("ssh clone failed");
        }
        mkdirSync(join(targetDir, ".git"), { recursive: true });
        return { stdout: "", stderr: "" };
      }
      throw new Error(`unexpected exec: ${cmd} ${args.join(" ")}`);
    });

    const result = await handleUrlStart("https://github.com/foo/new-repo");
    expect(result.autoGenerated).toBe(true);
    expect(result.parsed.ownerRepo).toBe("foo/new-repo");
    expect(gitCloneCalls).toBe(2);
  });

  it("uses gh repo clone when gh auth is available on github.com", async () => {
    const targetDir = join(workDir, "auth-repo");

    mockExecSilent.mockImplementation(async (cmd: string, args: string[]) => {
      if (cmd === "gh" && args.join(" ") === "auth status") return "logged in";
      return null;
    });

    mockExec.mockImplementation(async (cmd: string, args: string[]) => {
      if (cmd === "gh" && args[0] === "repo" && args[1] === "clone") {
        mkdirSync(join(targetDir, ".git"), { recursive: true });
        return { stdout: "", stderr: "" };
      }
      throw new Error(`unexpected exec: ${cmd} ${args.join(" ")}`);
    });

    const result = await handleUrlStart("https://github.com/foo/auth-repo");
    expect(result.autoGenerated).toBe(true);
    const ghCall = mockExec.mock.calls.find(([c]) => c === "gh");
    expect(ghCall).toBeDefined();
  });
});
