import { execFile } from "node:child_process";
import { mkdir, stat, writeFile } from "node:fs/promises";
import { join, resolve } from "node:path";
import { promisify } from "node:util";
import { NextResponse } from "next/server";
import { configToYaml, generateSessionPrefix, sanitizeProjectId } from "@composio/ao-core";
import { QuickStartProjectSchema } from "@/lib/api-schemas";
import { registerAndResolveProject } from "@/lib/project-registration";

const execFileAsync = promisify(execFile);

async function ensureDirectory(path: string): Promise<void> {
  await mkdir(path, { recursive: true });
}

async function ensureMissingOrEmptyDirectory(path: string): Promise<void> {
  try {
    const info = await stat(path);
    if (!info.isDirectory()) {
      throw new Error(`Target path exists and is not a directory: ${path}`);
    }
    throw new Error(`Target directory already exists: ${path}`);
  } catch (error) {
    if ((error as NodeJS.ErrnoException).code === "ENOENT") {
      return;
    }
    throw error;
  }
}

function buildAoConfig(projectName: string, projectId: string, targetDir: string) {
  return {
    port: 3000,
    defaults: {
      runtime: "tmux",
      agent: "claude-code",
      workspace: "worktree",
      notifiers: ["desktop"],
    },
    projects: {
      [projectId]: {
        name: projectName,
        path: targetDir,
        defaultBranch: "main",
        sessionPrefix: generateSessionPrefix(projectId),
      },
    },
  };
}

async function writeEmptyTemplate(targetDir: string, projectName: string): Promise<void> {
  await Promise.all([
    writeFile(
      join(targetDir, "README.md"),
      `# ${projectName}\n\nBootstrapped with Agent Orchestrator quick start.\n`,
      "utf-8",
    ),
    writeFile(join(targetDir, ".gitignore"), "node_modules\n.next\ndist\n.env\n", "utf-8"),
  ]);
}

async function writeNextJsTemplate(targetDir: string, projectName: string): Promise<void> {
  const packageJson = {
    name: sanitizeProjectId(projectName),
    version: "0.1.0",
    private: true,
    scripts: {
      dev: "next dev",
      build: "next build",
      start: "next start",
      lint: "next lint",
    },
    dependencies: {
      next: "^15.0.0",
      react: "^19.0.0",
      "react-dom": "^19.0.0",
    },
    devDependencies: {
      "@types/node": "^22.0.0",
      "@types/react": "^19.0.0",
      "@types/react-dom": "^19.0.0",
      typescript: "^5.0.0",
    },
  };

  await ensureDirectory(join(targetDir, "app"));

  await Promise.all([
    writeFile(join(targetDir, ".gitignore"), "node_modules\n.next\nout\n.env\n", "utf-8"),
    writeFile(join(targetDir, "package.json"), `${JSON.stringify(packageJson, null, 2)}\n`, "utf-8"),
    writeFile(
      join(targetDir, "tsconfig.json"),
      `${JSON.stringify(
        {
          compilerOptions: {
            target: "ES2017",
            lib: ["dom", "dom.iterable", "esnext"],
            allowJs: false,
            skipLibCheck: true,
            strict: true,
            noEmit: true,
            esModuleInterop: true,
            module: "esnext",
            moduleResolution: "bundler",
            resolveJsonModule: true,
            isolatedModules: true,
            jsx: "preserve",
            incremental: true,
            plugins: [{ name: "next" }],
          },
          include: ["next-env.d.ts", "**/*.ts", "**/*.tsx", ".next/types/**/*.ts"],
          exclude: ["node_modules"],
        },
        null,
        2,
      )}\n`,
      "utf-8",
    ),
    writeFile(
      join(targetDir, "next-env.d.ts"),
      '/// <reference types="next" />\n/// <reference types="next/image-types/global" />\n\n// This file is auto-generated by Next.js.\n',
      "utf-8",
    ),
    writeFile(
      join(targetDir, "next.config.ts"),
      "import type { NextConfig } from \"next\";\n\nconst nextConfig: NextConfig = {};\n\nexport default nextConfig;\n",
      "utf-8",
    ),
    writeFile(
      join(targetDir, "app", "globals.css"),
      ":root {\n  color-scheme: light;\n}\n\n* {\n  box-sizing: border-box;\n}\n\nhtml,\nbody {\n  margin: 0;\n  min-height: 100%;\n  font-family: ui-sans-serif, system-ui, sans-serif;\n  background: #f6f3ed;\n  color: #181616;\n}\n\na {\n  color: inherit;\n}\n",
      "utf-8",
    ),
    writeFile(
      join(targetDir, "app", "layout.tsx"),
      `import type { Metadata } from "next";\nimport "./globals.css";\n\nexport const metadata: Metadata = {\n  title: "${projectName}",\n  description: "Created with Agent Orchestrator quick start",\n};\n\nexport default function RootLayout({ children }: Readonly<{ children: React.ReactNode }>) {\n  return (\n    <html lang="en">\n      <body>{children}</body>\n    </html>\n  );\n}\n`,
      "utf-8",
    ),
    writeFile(
      join(targetDir, "app", "page.tsx"),
      `export default function Home() {\n  return (\n    <main style={{ minHeight: "100vh", display: "grid", placeItems: "center", padding: "32px" }}>\n      <section style={{ width: "100%", maxWidth: "720px", border: "1px solid rgba(24,22,22,0.12)", borderRadius: "24px", background: "#ffffff", padding: "32px", boxShadow: "0 20px 60px rgba(0,0,0,0.08)" }}>\n        <p style={{ margin: 0, fontSize: "12px", letterSpacing: "0.18em", textTransform: "uppercase", color: "#7b7468" }}>\n          Quick start\n        </p>\n        <h1 style={{ margin: "16px 0 0", fontSize: "48px", letterSpacing: "-0.06em" }}>\n          ${projectName}\n        </h1>\n        <p style={{ margin: "16px 0 0", fontSize: "16px", lineHeight: 1.7, color: "#534d43" }}>\n          This Next.js app was created by Agent Orchestrator. Start editing <code>app/page.tsx</code>.\n        </p>\n      </section>\n    </main>\n  );\n}\n`,
      "utf-8",
    ),
  ]);
}

export async function POST(request: Request) {
  try {
    const body = await request.json();
    const parsed = QuickStartProjectSchema.safeParse(body);
    if (!parsed.success) {
      return NextResponse.json(
        { error: parsed.error.issues[0]?.message ?? "Invalid quick start request" },
        { status: 400 },
      );
    }

    const projectId = sanitizeProjectId(parsed.data.name);
    if (!projectId) {
      return NextResponse.json({ error: "Name is required" }, { status: 400 });
    }

    const projectRoot = resolve(parsed.data.location);
    const targetDir = resolve(projectRoot, projectId);

    await ensureDirectory(projectRoot);
    await ensureMissingOrEmptyDirectory(targetDir);
    await ensureDirectory(targetDir);

    if (parsed.data.template === "nextjs") {
      await writeNextJsTemplate(targetDir, parsed.data.name.trim());
    } else {
      await writeEmptyTemplate(targetDir, parsed.data.name.trim());
    }

    const config = buildAoConfig(parsed.data.name.trim(), projectId, targetDir);
    await writeFile(join(targetDir, "agent-orchestrator.yaml"), `${configToYaml(config)}`, "utf-8");

    await execFileAsync("git", ["init", "-b", "main"], {
      cwd: targetDir,
      timeout: 30_000,
    }).catch(async () => {
      await execFileAsync("git", ["init"], {
        cwd: targetDir,
        timeout: 30_000,
      });
      await execFileAsync("git", ["branch", "-M", "main"], {
        cwd: targetDir,
        timeout: 30_000,
      });
    });

    const project = registerAndResolveProject(targetDir, {
      configProjectKey: projectId,
      displayName: parsed.data.name.trim(),
    });

    return NextResponse.json({
      project: {
        id: project.id,
        name: project.name,
        path: targetDir,
      },
    });
  } catch (err) {
    return NextResponse.json(
      { error: err instanceof Error ? err.message : "Failed to create project" },
      { status: 500 },
    );
  }
}
